name: Set up node and pnpm
description: Sets up node and installs dependencies with pnpm

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - run: pnpm install
      shell: bash
