name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-vsix.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Package VSIX
        id: package-vsix
        run: |
          pnpm package
          echo "version=$(jq --raw-output '.version' package.json)" >> "$GITHUB_OUTPUT"

      - name: Archive VSIX
        uses: actions/upload-artifact@v4
        with:
          name: vscodium-devpodcontainers.vsix
          path: vscodium-devpodcontainers-${{ steps.package-vsix.outputs.version }}.vsix

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Ensure new version
        run: |
          latest_tag=$(curl --silent -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/3timeslazy/vscodium-devpodcontainers/releases/latest | jq --raw-output '.tag_name')
          if [ "$latest_tag" = "v${{ needs.build.outputs.version }}" ]; then
            exit 1
          fi

      - uses: actions/download-artifact@v4
        with:
          name: vscodium-devpodcontainers.vsix
          path: vscodium-devpodcontainers-${{ needs.build.outputs.version }}.vsix

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          files: vscodium-devpodcontainers-${{ needs.build.outputs.version }}.vsix

      - name: Publish to Open VSX Registry
        run: |
          npx ovsx publish \
            --packagePath vscodium-devpodcontainers-${{ needs.build.outputs.version }} \
            --pat ${{ secrets.OPEN_VSX_TOKEN }}
